##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.15.2] date: [Tue Jun 28 20:41:40 MSK 2022]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = encoder_gd32


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og
OPT += -fsingle-precision-constant -Wdouble-promotion -freciprocal-math


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Src/main.c \
Src/gd32e23x_it.c \
Src/systick.c \
Drivers/CMSIS/GD/GD32E23x/Source/system_gd32e23x.c \
Drivers/GD32E23x_standard_peripheral/Source/gd32e23x_adc.c \
Drivers/GD32E23x_standard_peripheral/Source/gd32e23x_dbg.c \
Drivers/GD32E23x_standard_peripheral/Source/gd32e23x_dma.c \
Drivers/GD32E23x_standard_peripheral/Source/gd32e23x_exti.c \
Drivers/GD32E23x_standard_peripheral/Source/gd32e23x_fmc.c \
Drivers/GD32E23x_standard_peripheral/Source/gd32e23x_fwdgt.c \
Drivers/GD32E23x_standard_peripheral/Source/gd32e23x_gpio.c \
Drivers/GD32E23x_standard_peripheral/Source/gd32e23x_misc.c \
Drivers/GD32E23x_standard_peripheral/Source/gd32e23x_pmu.c \
Drivers/GD32E23x_standard_peripheral/Source/gd32e23x_rcu.c \
Drivers/GD32E23x_standard_peripheral/Source/gd32e23x_rtc.c \
Drivers/GD32E23x_standard_peripheral/Source/gd32e23x_timer.c \
Drivers/GD32E23x_standard_peripheral/Source/gd32e23x_usart.c \
Drivers/GD32E23x_standard_peripheral/Source/gd32e23x_spi.c \


# ASM sources
ASM_SOURCES =  \
startup_gd32e23x.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m23

# fpu
#FPU = -mfpu=fpv4-sp-d16

# float-abi
#FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-D_GNU_SOURCE \
-DGD32E23X \
-DUSE_STDPERIPH_DRIVER


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IInc \
-IDrivers/CMSIS \
-IDrivers/CMSIS/GD/GD32E23x/Include \
-IDrivers/GD32E23x_standard_peripheral/Include \
-Issd1306


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = GD32E230_FLASH.ld

# libraries
LIBS =
#LIBS = -lc -lm -lnosys
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections -Wl,--print-memory-usage
LDFLAGS	+= -Wl,--no-warn-rwx-segment

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***